### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by zeenk** [romdeau23/wow-mogpartialsets#1]
Message: Interface\AddOns\MogPartialSets\MogPartialSets.lua:670: Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
Time: Wed Jun  1 22:06:38 2022
Count: 1
Stack: Interface\AddOns\MogPartialSets\MogPartialSets.lua:670: Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
[string "=[C]"]: ?
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\MogPartialSets\MogPartialSets.lua"]:670: in function `tryFinally'
[string "@Interface\AddOns\MogPartialSets\MogPartialSets.lua"]:386: in function `GetUsableSets'
[string "@Interface\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua"]:3102: in function `GetUsableSets'
[string "@Interface\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua"]:4221: in function `GetFirstMatchingSetID'
[string "@Interface\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua"]:4080: in function <...ce\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua:4079>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\MogPartialSets\MogPartialSets.lua"]:451: in function `Refresh'
[string "@Interface\AddOns\Blizzard_Collections\Blizzard_Wardrobe.lua"]:4052: in function `OnEvent'
[string "@Interface\AddOns\MogPartialSets\MogPartialSets.lua"]:646: in function `refreshSetsFrame'
[string "@Interface\AddOns\MogPartialSets\MogPartialSets.lua"]:639: in function <Interface\AddOns\MogPartialSets\MogPartialSets.lua:638>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals:

**Comment by romdeau23** [comment]
This was fixed some time ago in e1de01bebccaef7e056c5ad270388b17bb45df21
