### ISSUE TITLE
Lua Errors with Pre-Patch

### ISSUE THREAD

**Issue by gz2k2** [romdeau23/wow-mogpartialsets#3]
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:120 Couldn't find inherited node: OptionsCheckButtonTemplate`
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:133 Couldn't find inherited node: OptionsCheckButtonTemplate`
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:146 Couldn't find inherited node: OptionsCheckButtonTemplate`
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:180 Couldn't find inherited node: OptionsCheckButtonTemplate`
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:193 Couldn't find inherited node: OptionsCheckButtonTemplate`
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:206 Couldn't find inherited node: OptionsCheckButtonTemplate`
`1x Interface/AddOns/MogPartialSets/MogPartialSets.xml:219 Couldn't find inherited node: OptionsCheckButtonTemplate`

**Comment by raysmith59** [comment]
Replace all instances of OptionsCheckButtonTemplate with SettingsCheckBoxControlTemplate and it should work.

**Comment by gz2k2** [comment]
thx!

**Comment by romdeau23** [comment]
Fixed in 2.0.0
