### ISSUE TITLE
Sets Window Issue when Extended Transmog Sets is also loaded

### ISSUE THREAD

**Issue by nancikennedy** [romdeau23/wow-mogpartialsets#4]
With both EST and MPS loaded at the same time, no mattter how long I've been logged in/transmog window is open, there is visual wierdness happening. Please see https://drive.google.com/file/d/1_SU6-w7_ZQydA2DtBWWbRzX2-s1pHHO-/view?usp=sharing for reference.

**Comment by romdeau23** [comment]
Hi, which addon is "EST"?

**Comment by nancikennedy** [comment]
Sorry, that should have been ETS (Extended Transmog Sets)

**Comment by romdeau23** [comment]
It should be fixed in 2.1.2, thanks for the report.

I can't guarantee these 2 addons will work 100% well together though 🙂
